### PR TITLE
twinwave: New App - initial app code import

### PR DESCRIPTION
**Pull request by twbryan**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [x] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- Initial import of twinwave app code

---
Thanks for contributing!

### CODE REVIEW

**Comment by twbryan** [comment]
At this point I'm not sure how to resolve the last two static test failures..

**Comment by arathore-crest** [comment]
Hello @twbryan,
We'll address the static test failures once we start working on this app.

Thanks, 
Aarav

**Comment by twbryan** [comment]
Thanks,

any sense of when that might be?

Thanks,
-Bryan

**Comment by arathore-crest** [comment]
@twbryan, we'll pick up this app based on our backlog.

Thanks,
Aarav

**Comment by dgopani-crest** [comment]
Hello @twbryan, we have made a few changes as per standard SOAR app practice, please review and approve the changes. We will move to further activities once you approved

**Comment by dgopani-crest** [comment]
Hello @twbryan, 
We have made a few changes as per SOAR app sandard practices. Can you please check the changes and approve them so we can move future with the release activities.

**Review by twbryan — COMMENTED** [review]
changes look good

**Comment by twbryan** [comment]
> Hello @twbryan,
> We have made a few changes as per SOAR app sandard practices. Can you please check the changes and approve them so we can move future with the release activities.

looks good!

**Review by rgil-splunk — APPROVED** [review]

**Review by ricardo-phantom — APPROVED** [review]

**Comment by mattsayar-splunk** [comment]
@twbryan We have a partner program in place where you have a little more control over your repository and publishing. Reach out to my email if you're interested msayar@splunk.com

**Pull request merged**
